export const FETCH_USERS_INPROGRESS = "FETCH_USERS_INPROGRESS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

export const DELETE_USERS_INPROGRESS = "DELETE_USERS_INPROGRESS";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export const DELETE_USERS_ERROR = "DELETE_USERS_ERROR";

export const CREATE_USERS_INPROGRESS = "CREATE_USERS_INPROGRESS";
export const CREATE_USERS_SUCCESS = "CREATE_USERS_SUCCESS";
export const CREATE_USERS_ERROR = "CREATE_USERS_ERROR";